# Generated by Django 4.2.3 on 2023-07-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0009_category_is_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
