# Generated by Django 4.2.3 on 2023-07-25 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0010_alter_product_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_app.product')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_app.saleitem')),
            ],
        ),
    ]
