# Generated by Django 4.2.3 on 2023-07-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0011_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='sale',
        ),
        migrations.AddField(
            model_name='sale',
            name='dateFrom',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='dateTo',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='salePrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
