# Generated by Django 4.2.3 on 2023-07-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0012_remove_sale_sale_sale_datefrom_sale_dateto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='dateFrom',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='dateTo',
            field=models.DateField(),
        ),
    ]
