# Generated by Django 4.2.3 on 2023-07-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0013_alter_sale_datefrom_alter_sale_dateto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='salePrice',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
