# Generated by Django 4.2.3 on 2023-08-13 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0014_alter_sale_saleprice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaleItem',
        ),
    ]
