# Generated by Django 4.2.3 on 2023-08-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0015_delete_saleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='oldPrice',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
