# Generated by Django 4.2.3 on 2023-08-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0016_sale_oldprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='oldPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
