# Generated by Django 4.2.3 on 2023-08-13 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0018_sale_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='is_active',
            new_name='is_applied',
        ),
    ]
