# Generated by Django 4.2.3 on 2023-08-13 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0020_sale_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcategories',
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='api_app.image')),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.category')),
            ],
        ),
    ]
