# Generated by Django 4.2.3 on 2023-08-16 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0022_rename_parent_category_subcategory_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_child',
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api_app.category'),
        ),
    ]
