# Generated by Django 4.2.3 on 2023-08-16 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_app', '0024_alter_product_images_alter_product_tags_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basket',
            options={'verbose_name': 'Basket', 'verbose_name_plural': 'Baskets'},
        ),
        migrations.AlterModelOptions(
            name='catalog',
            options={'verbose_name': 'Catalog', 'verbose_name_plural': 'Catalogs'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderhistory',
            options={'verbose_name': "Order's history", 'verbose_name_plural': "Order's histories"},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Order <-> Product', 'verbose_name_plural': 'Orders <-> Products'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
        migrations.AlterModelOptions(
            name='specification',
            options={'verbose_name': 'Specification', 'verbose_name_plural': 'Specifications'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Subcategory', 'verbose_name_plural': 'Subcategories'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='basket',
            name='count',
            field=models.IntegerField(verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='items',
            field=models.ManyToManyField(to='api_app.product', verbose_name='Items'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api_app.image', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='image',
            name='alt',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.CharField(blank=True, max_length=255, verbose_name='Path to img'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='order',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliveryType',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Delivery type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fullName',
            field=models.CharField(max_length=255, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentType',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='api_app.orderproduct', verbose_name='Products'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='totalCost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total cost'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='count',
            field=models.IntegerField(verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='code',
            field=models.CharField(max_length=3, verbose_name='CVC code'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='month',
            field=models.CharField(max_length=2, verbose_name='Expiration month'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Cardholder name'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='number',
            field=models.CharField(max_length=16, verbose_name='Card number'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='year',
            field=models.CharField(max_length=4, verbose_name='Expiration year'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.IntegerField(verbose_name='Count'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Change date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='freeDelivery',
            field=models.BooleanField(verbose_name='Free delivery'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fullDescription',
            field=models.TextField(verbose_name='Full description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(related_name='images', to='api_app.image', verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_limited',
            field=models.BooleanField(default=False, verbose_name='Is limited'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reviews',
            field=models.ManyToManyField(to='api_app.review', verbose_name='Reviews'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sold',
            field=models.IntegerField(default=0, verbose_name='Sold'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.ManyToManyField(to='api_app.specification', verbose_name='Specifications'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='api_app.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='review',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='review',
            name='email',
            field=models.CharField(max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.IntegerField(verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(verbose_name='Review text'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='dateFrom',
            field=models.DateField(verbose_name='Sale starts'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='dateTo',
            field=models.DateField(verbose_name='Sale ends'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='is_applied',
            field=models.BooleanField(default=False, verbose_name='Is applied'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='oldPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Old price'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api_app.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='salePrice',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sale price'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='value',
            field=models.CharField(max_length=100, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='api_app.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='api_app.image', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.DeleteModel(
            name='CatalogItem',
        ),
    ]
