# Generated by Django 4.2.3 on 2023-08-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0028_alter_order_email_alter_order_fullname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AlterField(
            model_name='product',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='api_app.review', verbose_name='Reviews'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.ManyToManyField(blank=True, to='api_app.specification', verbose_name='Specifications'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
